var autosysConfig = {
	"triggerName" : "触发器名称",
	"taketime" : "耗时(s)",
	"startDetail" : "start信息",
	"endDetail" : "end信息",
	"status" : "状态",
	"triggerGroup" : "触发器组",
	"triggerDescription" : "功能",
	"startTime" : "开始时间",
	"endTime" : "结束时间",
	"nextFireTime" : "下次触发时间",
	"prevFireTime" : "触发时间",
	"priority" : "priority",
	"triggerState" : "触发器状态",
	"triggerType" : "触发器类型",
	"calendarName" : "时区名称",
	"misfireInstr" : "misfireInstr",
	"triggerJobData" : "trigger配置数据",
	"jobName" : "JOB名称",
	"jobGroup" : "JOB组",
	"schedName" : "调度器名称",
	"description" : "功能",
	"jobClassName" : "JOB class 名称",
	"isDurable" : "是否持久化",
	"isNonconcurrent" : "是否可并发",
	"isUpdateData" : "isUpdateData",
	"requestsRecovery" : "执行失败,是否即可重新执行",
	"jobData" : "job配置数据"
}
